{{- if eq .Values.agent.agentType "lorawan" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "iot-agent.name" . }}
    component: "{{ .Values.agent.agentType }}"
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "iot-agent.fullname" . }}
data:
  config.js: |
    var config = {};

    config.iota = {
        logLevel:  {{ .Values.agent.logLevel | default "DEBUG" | quote }},
        timestamp:  {{ .Values.agent.timestamp | default true }},
        contextBroker: {
            host: {{ required "A valid contextBroker.host is required" .Values.contextBroker.host | quote }},
            port: {{ required "A valid contextBroker.port is required" .Values.contextBroker.port }},
            ngsiVersion: {{ .Values.contextBroker.ngsiVersion | quote }}
        },
        server: {
            port: {{ required "A valid service.configInternalPort is required" .Values.service.configInternalPort }},
            baseRoot: '/config'
        },
        deviceRegistry: {
            type: 'mongodb'
        },
        mongodb: {
            host: {{ required "A valid mongo.dbhost is required" .Values.mongo.dbhost | quote }},
            port: {{ required "A valid mongo.dbport is required" .Values.mongo.dbport }},
            db: {{ required "A valid mongo.dbname is required" .Values.mongo.dbname | quote }},
            {{ if .Values.mongo.rsEnabled -}}replicaSet: {{ .Values.mongo.rs | quote }}{{- end }}
        },
        {{- if .Values.iotManager.enabled }}
        iotManager: {
          host: {{ .Values.iotManager.host | quote }},
          port: {{ .Values.iotManager.port }},
          path: {{ .Values.iotManager.path | quote }},
          protocol: {{ .Values.iotManager.protocol | quote }},
          description: {{ .Values.iotManager.description | default "A generic protocol" | quote }},
          agentPath: {{ .Values.iotManager.agentPath | default "/iot" | quote }}
        },
        {{- end }}
        /**
         * Default resource of the IoT Agent. This value must be different for every IoT Agent connecting to the IoT
         * Manager.
         */
        defaultResource: '/iot/{{ .Release.Name }}',
        types: {{ toJson .Values.types }},
        service: {{ required "A valid agent.defaultService is required" .Values.agent.defaultService | quote }},
        subservice: {{ required "A valid agent.defaultSubservice is required" .Values.agent.defaultSubservice | quote }},
        {{- if .Values.agent.providerUrl }}
        providerUrl: {{ .Values.agent.providerUrl | quote }},
        {{- else if .Values.ingress.enabled }}
        providerUrl: 'https://{{ index .Values.ingress.hosts 0 }}/config',
        {{- else }}
        providerUrl: 'http://{{ .Release.Name }}-{{ template "iot-agent.name" . }}.{{ .Release.Namespace }}:{{ .Values.service.configExternalPort }}'
        {{- end }}
        {{- if .Values.agent.autocast }}
        autocast: {{ .Values.agent.autocast }},
        {{- end }}
        deviceRegistrationDuration: {{ required "A valid agent.deviceRegistrationDuration is required" .Values.agent.deviceRegistrationDuration | quote }},
        defaultType: {{ required "A valid agent.defaultType is required" .Values.agent.defaultType | quote }},
        /**
         * flag indicating whether the incoming measures to the IoTAgent should be processed as per the "attributes" field.
         */
        explicitAttrs: {{ .Values.agent.explicitAttrs | default false }}
    };

    /**
     * flag indicating whether the incoming notifications to the IoTAgent should be processed using the bidirectionality
     * plugin from the latest versions of the library or the UL-specific configuration retrieval mechanism.
     */
    config.configRetrieval = {{ .Values.agent.configRetrieval | default false }};

    config.defaultKey = '{{ required "A valid agent.defaultKey is required" .Values.agent.defaultKey }}';
    config.defaultTransport = '{{ required "A valid agent.defaultTransport is required" .Values.agent.defaultTransport }}';
    /**
     * flag indicating whether the node server will be executed in multi-core option (true) or it will be a
     * single-thread one (false).
     */
    config.multiCore = {{ .Values.agent.multiCore | default true }};
    config.defaultExpressionLanguage = {{ .Values.agent.defaultExpressionLanguage }};
    module.exports = config;

{{- end -}}
