apiVersion: v1
description: A Helm chart for QuantumLeap
name: quantumleap
appVersion: "0.8.x"
version: 0.1.11
sources:
- https://github.com/smartsdk/ngsi-timeseries-api
maintainers:
- name: chicco785
  email: federico.facca@martel-innovate.com